Milestone 3: Game logic
Ceci007/Tic-Tac-Toe pull request #5
Opened 2020-09-03 20:42 UTC by Ceci007

## Milestone 3: Game logic 
This is the game logic we implemented:
- Add real logic to the game.
- Class Player implementation. 
- Class Board implementation.
- Using classes in the main file and connecting them.
- Using the "single responsibility" rule.

2020-09-03 21:24 UTC, krys2fa requested changes
## Nicely done @jelduran and @Ceci007  👏 
You have very detailed and descriptive commit messages. 💪 
Your README file is also taking shape already. 👍 

Just a few more adjustments to complete this milestone. They can be seen below as well as in the comments:
### Status: Changes Required ♻️ 

- [ ] [REQUIRED] Your application allows players to move into already occupied positions. Please fix this.

- [ ] [OPTIONAL] It would be nice to have the game allow players to play again when a game comes to an end.

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-09-03 21:24 UTC, krys2fa commented on lib/board.rb
> +     " #{@positions[2][0]} | #{@positions[2][1]} | #{@positions[2][2]} \n"
- [ ] [REQUIRED] There should be no `puts/print` and `get.chomp` outside the `main.rb` file.

2020-09-03 21:24 UTC, krys2fa commented on lib/player.rb
> +  attr_accessor :name, :mark
- [ ] [REQUIRED] You should use attr_readers/attr_writers. Only use attr_accessors if you really have to since using it allows this property to be written to from outside this class ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)).

2020-09-03 21:24 UTC, krys2fa commented on bin/main.rb
> +require './lib/board'
- [ ] [OPTIONAL] It is a ruby convention to use `require_relative` instead of `require`. `require` should be used for external files like gems while `require_relative` should be used for referencing files in your project directory.

2020-09-04 18:23 UTC, mosesogwo approved these changes
**Great! :clap: You are now fit to :rocket:**

_**Cheers:stars:**_

### Status: Approved :heavy_check_mark:

2020-09-04 19:06 UTC, merged